version: "3"
services:
 elasticsearch:
   image: elasticsearch:5.6
   ports: 
     - 9200:9200
     - 9300:9300
   environment:
    - discovery.type=single-node

 grafana:
  image: grafana/grafana:5.1.0
  container_name: grafana
  environment:
   - GF_SERVER_ROOT_URL=http://localhost
   - GF_SECURITY_ADMIN_PASSWORD=123456
   - TZ="America/Bahia"
  ports:
   - 3000:3000
  user: "104"